version: '3.9'

services:
  controlefluxocaixa.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - DB_SERVER=sql-primary
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=sa
    ports:
      - "8080:8080"  # Mapeia porta HTTP do container para localhost
      - "8081:8081"  # Mapeia porta HTTPS do container para localhost
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  controlefluxocaixa.worker.mensageria.transacao:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_SERVER=sql-primary
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=sa
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro